### ISSUE TITLE
Add GenericSVD.jl here?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLinearAlgebra/GenericLinearAlgebra.jl#20]
It seems like it fits nicely here, and there is no need to have it as a separate package. @simonbyrne

**Comment by ChrisRackauckas** [comment]
There is mention of and SVD solver here, what's the difference?

**Comment by simonbyrne** [comment]
This package isn't registered: I get the impression that it is a bit experimental 

GenericSVD.jl was based on this code, but has a bit more polish, and deals with a few more edge cases.

**Comment by simonbyrne** [comment]
Now it has been registered, this would probably be a good idea.

**Comment by andreasnoack** [comment]
This package is now registered and I think the svd here covers the same functionality as GenericSVD so I'll close.

**Comment by olof3** [comment]
It seems like some things that were fixed in the `GenericSVD` package are still broken in this package, for example that the `full` kwarg is respected 
```julia
using GenericLinearAlgebra
svd(big.(randn(5,2)), full=true)
```
I guess there could be others as well.

Some simple tests that perhaps could be reused are found here
https://github.com/JuliaLinearAlgebra/GenericSVD.jl/pull/20/files

**Comment by simonbyrne** [comment]
Added support for `full` in #73.
